# Generated by Django 6.0.6 on 2026-06-15 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel des Quiz', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Beschreibung des Quiz')),
                ('video_url', models.URLField(help_text='URL zum YouTube-Video')),
                ('status', models.CharField(choices=[('processing', 'Wird verarbeitet'), ('completed', 'Fertig'), ('failed', 'Fehler')], default='processing', help_text='Verarbeitungsstatus des Quiz', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitstempel der Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitstempel der letzten Änderung')),
                ('owner', models.ForeignKey(help_text='Der Benutzer, dem das Quiz gehört', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(help_text='Der Fragetext', max_length=500)),
                ('question_options', models.JSONField(help_text='Liste mit 4 Antwortmöglichkeiten als JSON Array')),
                ('answer', models.CharField(help_text='Die richtige Antwort', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitstempel der Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitstempel der letzten Änderung')),
                ('quiz', models.ForeignKey(help_text='Zugehöriges Quiz', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes_app.quiz')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('download_started', 'Download gestartet'), ('download_completed', 'Download fertig'), ('transcription_started', 'Transkription gestartet'), ('transcription_completed', 'Transkription fertig'), ('generation_started', 'Quiz-Generierung gestartet'), ('generation_completed', 'Quiz-Generierung fertig'), ('error', 'Fehler aufgetreten'), ('completed', 'Vollständig verarbeitet')], help_text='Status des Verarbeitungsschritts', max_length=30)),
                ('message', models.TextField(blank=True, default='', help_text='Nachricht oder Error-Details')),
                ('error_details', models.JSONField(blank=True, help_text='Detaillierte Error-Informationen falls Fehler', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitstempel des Log-Eintrags')),
                ('quiz', models.ForeignKey(help_text='Zugehöriges Quiz', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='quizzes_app.quiz')),
            ],
            options={
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Rohtext des Transkripts von Whisper')),
                ('duration', models.IntegerField(blank=True, help_text='Länge des Videos in Sekunden', null=True)),
                ('language', models.CharField(default='de', help_text="Erkannte Sprache (z.B. 'de', 'en')", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitstempel der Transkription')),
                ('quiz', models.OneToOneField(help_text='Zugehöriges Quiz', on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='quizzes_app.quiz')),
            ],
            options={
                'verbose_name_plural': 'Transcripts',
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['owner', '-created_at'], name='quizzes_app_owner_i_8425fd_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz'], name='quizzes_app_quiz_id_0c1b37_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['quiz', '-created_at'], name='quizzes_app_quiz_id_272d55_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['status'], name='quizzes_app_status_07a06b_idx'),
        ),
    ]
